### ISSUE TITLE
Consider using a Brewfile for Homebrew installs

### ISSUE THREAD

**Issue by bbkane** [protiumx/.dotfiles#1]
I saw your Medium post and you said you welcomed suggestions😁

I feel like Brewfiles are a bit more declarative and have fewer foot guns than shell scripts, but unless you're feeling especially chipper it might not be worth the work to replace your working brew install  shell script.

See https://github.com/Homebrew/homebrew-bundle or https://thoughtbot.com/blog/brewfile-a-gemfile-but-for-homebrew for examples.

**Comment by protiumx** [comment]
It looks neat! Although my objective was to have as less dependencies as possible to get my environment set up, for instance `mas` is already one dependency that I'd only use during setup.

Thanks for the suggestion!
